/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SheettestRouteImport } from './routes/sheettest'
import { Route as IndexRouteImport } from './routes/index'

const SheettestRoute = SheettestRouteImport.update({
  id: '/sheettest',
  path: '/sheettest',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sheettest': typeof SheettestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sheettest': typeof SheettestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sheettest': typeof SheettestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sheettest'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sheettest'
  id: '__root__' | '/' | '/sheettest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SheettestRoute: typeof SheettestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sheettest': {
      id: '/sheettest'
      path: '/sheettest'
      fullPath: '/sheettest'
      preLoaderRoute: typeof SheettestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SheettestRoute: SheettestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
